codingchallenge/application/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    path('', login_required(views.TaskForAddressListView.as_view()), name="wall"),
    path('task/<int:pk>', login_required(views.TaskDetailView.as_view()), name="task_detail"),
    path('profile/', login_required(views.ProfileView.as_view()), name="profile"),
    path('task-create/', login_required(views.TaskCreateView.as_view()), name="task_create"),
    path('assign-view/<int:pk>', views.assign_task_view, name="task_assign"),
    path('assign-auth-view/<int:pk>', views.AuthenticateForChangeTask.as_view(), name="task_authenticate_assign"),
    path('mark-done-view/<int:pk>',views.task_mark_done, name="task_mark_done"),
    path('accept-done-view/<int:pk>',views.task_accept_done, name="task_accept_done"),
    path('history/', login_required(views.ProfileHistoryView.as_view()), name="history"),
    path('messages/', login_required(views.MessagesView.as_view()), name="messages")
]

codingchallenge/codingchallenge/urls.py
from django.contrib import admin
from django.urls import path, include
import django.contrib.auth.views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('application.urls')),
    path('login/', auth_views.LoginView.as_view(template_name="application/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
]

codingchallenge/application/models.py
from django.db import models
from django.contrib.auth.models import User

class Address(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Task(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE, related_name="tasks_assigned")
    value = models.PositiveIntegerField()
    pub_date = models.DateTimeField(auto_now_add=True)
    mod_date = models.DateTimeField(auto_now=True)

    ADDED = 'DODANE'
    ASSIGNED = 'PRZYPISANE'
    DONE = 'WYKONANE'
    APPROVED = 'POTWIERDZONE'

    STATUSES = (
        (ADDED, "Dodane"),
        (ASSIGNED, "Przypisane"),
        (DONE, "Wykonane"),
        (APPROVED, "Potwierdzone"),
    )

    status = models.CharField(
        max_length=12,
        choices = STATUSES,
        default = ADDED
    )

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    flat_number = models.PositiveIntegerField()

    def __str__(self):
        return self.user.username + "'s profile"

class Message(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    address = models.ForeignKey(Address, on_delete=models.CASCADE, null=True)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

codingchallenge/application/forms.py
from django import forms
from django.contrib.auth.models import User


class AuthenticateForm(forms.Form):
    username = forms.CharField(label="username", max_length=30)
    password = forms.CharField(label="password", max_length=30, widget=forms.PasswordInput)

codingchallenge/application/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.db.models import Q, Sum
from django.views.generic.edit import CreateView, FormView
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required, permission_required
from django import http
from django.urls import reverse_lazy
from django import forms

from .forms import AuthenticateForm
from .models import Task, Address, Message

@login_required
def index(request):
    return render(request, "application/index.html")

@login_required
def assign_task_view(request,pk):
    task=Task.objects.get(pk=pk)
    task.receiver=request.user
    task.status = Task.ASSIGNED
    task.save()
    return redirect("profile")

def task_mark_done(request,pk):
    task=Task.objects.get(pk=pk)
    task.status = Task.DONE
    task.save()
    return redirect("profile")

def task_accept_done(request,pk):
    task=Task.objects.get(pk=pk)
    task.status = Task.APPROVED
    task.save()
    return redirect("profile")

class TaskForAddressListView(ListView):

    def get_queryset(self):
        return Task.objects.filter(
            client__userprofile__address=self.request.user.userprofile.address
        ).filter(receiver__isnull=True)

    context_object_name = "all_tasks"

    template_name = "application/index.html"

class TaskDetailView(DetailView):

    model = Task


class ProfileView(ListView):

    model = Task

    def get_context_data(self, **kwargs):
        u = self.request.user
        context = super().get_context_data(**kwargs)

        context['tasks_client'] = context['tasks'].filter(client=u).exclude(status=Task.APPROVED).order_by('-status')
        context['tasks_receiver'] = context['tasks'].filter(receiver=u).exclude(status=Task.APPROVED).order_by('status')

        plus = Task.objects.filter(receiver=u).filter(status=Task.APPROVED).aggregate(Sum('value'))['value__sum']
        if plus == None:
            plus = 0
        minus = Task.objects.filter(client=u).aggregate(Sum('value'))['value__sum']
        if minus == None:
            minus = 0
        context['user_points'] = plus - minus + 100
        return context

    context_object_name = 'tasks'

    template_name = "application/profile.html"

class ProfileHistoryView(ListView):

    model = Task

    def get_context_data(self, **kwargs):
        u = self.request.user
        context = super().get_context_data(**kwargs)

        context['tasks_client'] = context['tasks'].filter(client=u).filter(status=Task.APPROVED).order_by('-mod_date')
        context['tasks_receiver'] = context['tasks'].filter(receiver=u).filter(status=Task.APPROVED).order_by('-mod_date')
        return context

    context_object_name = 'tasks'

    template_name = "application/history.html"

class TaskCreateView(CreateView):

    model = Task
    fields = ["title", "description", "value"]

    def form_valid(self, form):
        task = form.save(commit=False)
        task.client = self.request.user

        plus = Task.objects.filter(receiver=task.client).filter(status=Task.APPROVED).aggregate(Sum('value'))['value__sum']
        if plus == None:
            plus = 0
        minus = Task.objects.filter(client=task.client).aggregate(Sum('value'))['value__sum']
        if minus == None:
            minus = 0
        points = plus - minus + 100
        if points - task.value >=0:
            task.save()
            return redirect("wall")
        else:
            form.add_error('value', 'Masz za mało punktów, aby dodać to zadanie.')
            return super().form_invalid(form)

    def get_form(self):
        form = super().get_form()
        form.fields['description'].widget = forms.Textarea(attrs={"class": "materialize-textarea"})
        form.fields['value'].widget = forms.NumberInput(attrs={"type": "range"})
        return form

class MessagesView(ListView):

    def get_queryset(self):
        u = self.request.user
        return Message.objects.filter(
            address=u.userprofile.address).order_by('-pub_date')

    context_object_name = "messages"

    template_name = "application/messages.html"


class AuthenticateForChangeTask(FormView):

    template_name = "application/login.html"
    form_class = AuthenticateForm

    def form_valid(self, form):
        cd = form.cleaned_data
        user = authenticate(username=cd["username"], password=cd["password"])
        if user is not None:
            task=Task.objects.get(pk=self.kwargs['pk'])
            task.receiver=user
            task.status = Task.ASSIGNED
            task.save()
            return redirect("wall")
        else:
            return redirect("")

codingchallenge/application/templates/application/history.html
{% extends "application/profile.html" %}
{% load static %}

{% block title %}
<title> Historia zadań użytkownika</title>
{% endblock title %}

{% block main %}
<main>
    <div class="container">
        <div class="row">
            <div class="col s12">
                <h1> Historia zadań użytkownika {{user.username}} </h1>
            </div>
        </div>

        <div class="row">
            <div class="col s12 m12 l6">
                <table class="highlight">
                    <thead>
                        <h4 class="black-text text-lighten-3 center-align"> Ukończone zlecone zadania </h4>
                    </thead>
                    <tbody>
                    {% for task in tasks_client %}
                    <tr>
                        <td>
                            <div class="row" style="margin-bottom: 0px;">
                                <div class="col s9">  <a class="black-text" href="{% url 'task_detail' task.pk %}"> <span class="flow-text"> {{ task.title }}</span> </a> </div>
                                <div class="col s3"> <span class="flow-text right"> <i class="material-icons">star</i> {{task.value}} </span> </div>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="col s12 m12 l6">
                <table class="highlight">
                    <thead>
                        <h4 class="black-text text-lighten-3 center-align"> Ukończone wykonane zadania </h4>
                    </thead>
                    <tbody>
                    {% for task in tasks_receiver %}
                    <tr>
                        <td>
                            <div class="row" style="margin-bottom: 0px;">
                                <div class="col s9"> <a class="black-text" href="{% url 'task_detail' task.pk %}"> <span class="flow-text"> {{ task.title }} </span></a> </div>
                                <div class="col s3"> <span class="flow-text right"> <i class="material-icons">star</i> {{task.value}} </span> </div>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>

{% endblock main %}

codingchallenge/application/templates/application/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>

	{% block title %}
	<title>Wesoła 1</title>
	{% endblock title %}

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href='{% static "application/css/materialize.css" %}' type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href='{% static "application/css/style.css" %}' type="text/css" rel="stylesheet" media="screen,projection"/>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" crossorigin="anonymous">
</head>
<body>
   {% block header %}
      <nav class="indigo">
        <div class="nav-wrapper container text-black">
            <a id="logo-container" href="{% url 'wall' %}" class="brand-logo"><i class="fas fa-home fa-lg"></i>{{ user.userprofile.address.name }}</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'messages' %}"><i class="fas fa-scroll"></i> Ogłoszenia</a></li>
                {% if perms.application.add_task %}
                <li><a href="{% url 'profile' %}"><i class="fas fa-user-circle fa-lg"></i> {{user.username}} </a></li>
                {% endif %}
            </ul>
        </div>
      </nav>
  {% endblock header %}

  {% block main %}
   <main>
       <div class="container">
           <div class="row">
               <div class="col s8 offset-s2">
                   <div class="row">
                       <table class="highlight">
                            <thead>
                                <h2 class="center-align"> Aktualne zadania </h2>
                            </thead>
                            <tbody>
                            {% for task in all_tasks %}
                            <tr>
                                <td style="padding-left: 5%;padding-right: 5%;">
                                    <div class="row" style="margin-bottom: 0px;">
                                        <div class="col s9"> <a href = {% url 'task_detail' task.pk %} class="indigo-text"> <span class="flow-text"> {{ task.title }} </span></a> </div>
                                        <div class="col s3"> <span class="flow-text right"> <i class="material-icons">star</i> {{task.value}} </span> </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                    {% if perms.application.add_task %}
                    <div class="row" style="padding-right: 5%;" >
                        <a href="{% url 'task_create' %}" class="btn-floating btn-large waves-effect waves-light indigo right"><i class="material-icons">add</i></a>
                    </div>
                    {% endif %}
               </div>
           </div>
       </div>
   </main>
   {% endblock main %}

	{% block footer %}
  <footer class="page-footer indigo">
      <div class="container">
          <div class="row">
              Made by <a class="white-text text-lighten-3" href="http://materializecss.com">Materialize</a> and Gauss Team :)))))
          </div>
      </div>
  </footer>
	{% endblock footer %}

  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src= '{% static "application/js/materialize.js" %}'></script>
  <script src= '{% static "js/init.js" %}'></script>
</body>

codingchallenge/application/templates/application/login.html
{% extends "application/index.html" %}
{% load static %}

{% block title %}
<title> Logowanie </title>
{% endblock title %}

{% block header %}
<nav class="indigo">
        <div class="nav-wrapper container text-black">
          <a id="logo-container" href="/1" class="brand-logo center">Logowanie</a>
        </div>
      </nav>
{% endblock header %}

{% block main %}
<main>
  <div class="container" style="position: relative;top: 25%;bottom: 25%;">
    <div class="row">
      <div class="col s12 m8 l4 offset-m2 offset-l4">
        <div class="card">
          <div class="card-content">
            {% if next %}
            <span class="card-title">Musisz się zalogować, aby zobaczyć tą stronę</span>
            {% endif %}
            <form method="post">
              {% csrf_token %}
              <div class="row">
                <div class="input-field col s12">
                  {{ form.username.errors }} {{ form.username }}
                  <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
                </div>
              </div>
              <div class="row">
                <div class="input-field col s12">
                  {{ form.password.errors }} {{ form.password }}
                  <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
                </div>
              </div>
              <div class="center-align">
                <button class="btn waves-effect waves-light indigo " type="submit" value="login">Zaloguj
                </button>
              </div>

              <input type="hidden" name="next" value="{{ next }}">

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</main>
{% endblock main %}

codingchallenge/application/templates/application/messages.html
{% extends "application/index.html" %}

	{% block title %}
	<title>Wesoła 1</title>
	{% endblock title %}

  {% block main %}
   <main>
       <div class="container">
           <div class="row">
               <div class="col s8 offset-s2">
                   <div class="row">
                       <table class="highlight">
                            <thead>
                                <h2 class="center-align"> Ogłoszenia </h2>
                            </thead>
                            <tbody>
                            {% for message in messages %}
                            <tr>
                                <td style="padding-left: 5%;padding-right: 5%;">
                                    <div class="row" style="margin-bottom: 0px;">
                                        <div class="col s9"> <span class="flow-text"> {{ message.title }} </span></a> </div>
                                        <div class="col s9"> <span class="flow-text"> {{ message.content }} </span></a> </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
               </div>
           </div>
       </div>
   </main>
   {% endblock main %}

codingchallenge/application/templates/application/profile.html
{% extends "application/index.html" %}
{% load static %}

{% block title %}
<title> Profil użytkownika</title>
{% endblock title %}

{% block header %}
      <nav class="indigo">
        <div class="nav-wrapper container text-black">
            <a id="logo-container" href="{% url 'wall' %}" class="brand-logo"><i class="fas fa-home fa-lg"></i>{{ user.userprofile.address.name }}</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'messages' %}"><i class="fas fa-scroll"></i> Ogłoszenia</a></li>
                <li><a href="{% url 'history' %}"><i class="fas fa-archive fa-lg"></i> Historia </a></li>
                <li><a href="{% url 'profile' %}"><i class="fas fa-user-circle fa-lg"></i> {{user.username}} </a></li>
                <li><a href="{% url 'logout' %}"><i class="fas fa-sign-out-alt fa-lg"></i> Wyloguj </a></li>
            </ul>

        </div>
      </nav>
  {% endblock header %}

{% block main %}
<main>
    <div class="container">
        <div class="row">
            <div class="col s12">
                <h1> Witaj {{user.username}} </h1>
                <h4> Twoja ilość punktów: {{user_points}} </h4>
            </div>
        </div>

        <div class="row">
            <div class="col s12 m12 l6">
                <table class="highlight">
                    <thead>
                        <h4 class="black-text text-lighten-3 center-align"> Zlecone zadania </h4>
                    </thead>
                    <tbody>
                    {% for task in tasks_client %}
                    <tr>
                        <td style="padding-left: 5%;padding-right: 5%;" >
                            <div class="row" style="margin-bottom: 0px;">
                                <div class="col s9">  <a class="indigo-text" href="{% url 'task_detail' task.pk %}"> <span class="flow-text"> {{ task.title }}</span> </a> </div>
                                <div class="col s3">
                                    {% if task.status == task.DONE and task.client == user%}
									<form action="{% url 'task_accept_done' task.pk %}" method="POST">
									{% csrf_token %}
									<button class="btn waves-effect waves-light indigo lighten-1" type="submit">Wykonane</button>
									</form>
								{% else %}
                                    <span class="flow-text"> {{task.status}} </span>
								{% endif %}
                                </div>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="col s12 m12 l6">
                <table class="highlight">
                    <thead>
                        <h4 class="black-text text-lighten-3 center-align"> Wzięte zadania </h4>
                    </thead>
                    <tbody>
                    {% for task in tasks_receiver %}
                    <tr>
                        <td style="padding-left: 5%;padding-right: 5%;">
                            <div class="row" style="margin-bottom: 0px;">
                                <div class="col s9"> <a class="indigo-text" href="{% url 'task_detail' task.pk %}"> <span class="flow-text"> {{ task.title }} </span></a> </div>
                                <div class="col s3">
                                    {% if task.status == task.ASSIGNED and task.receiver == user%}
                                    <form action="{% url 'task_mark_done' task.pk %}" method="POST">
                                    {% csrf_token %}
                                    <button class="btn waves-effect waves-light indigo lighten-1" type="submit">Zrobione </button>
                                    </form>
                                    {% else %}
                                        <span class="flow-text"> {{ task.status }} </span>
                                    {% endif %}
                                </div>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>

{% endblock main %}

codingchallenge/application/templates/application/task_detail.html
{% extends "application/index.html" %}

{% block title %}
<title> {{task.title }} </title>
{% endblock title %}

{% block main %}
<main>
    <div class="container">
        <div class="row">
            <div class="col s8 offset-s2">
                <div class="row">
                    <div class="col s12"> <h1>{{ task.title }}</h1> </div>
                </div>
                <div class="row">
                    <div class="col s12"> <h4> Punkty:</h4></div>
                    <div class="col s12"> <span class="flow-text"> <i class="material-icons">star</i> {{task.value}} </span> </div>
                </div>
                <div class="row">
                    <div class="col s12"> <h4> Opis zadania:</h4></div>
                    <div class="col s12"> <span class="flow-text"style="font-size: 1.5em" > {{task.description}} </span> </div>
                </div>
                <div class="row">
                    <div class="col s12"> <h4> Data dodania:</h4></div>
                    <div class="col s12"> <span class="flow-text"style="font-size: 1.5em" > {{task.pub_date}} </span> </div>
                </div>
                <div class="row">
                    <div class="col s12"> <h4> Autor zadania:</h4></div>
                    <div class="col s12"> <span class="flow-text" style="font-size: 1.5em"> {{task.client.username }} (mieszkanie nr {{ task.client.userprofile.flat_number}}) </span> </div>
                </div>

                <div class="row">
                {% if task.receiver == None and task.client != user %}
                    {% if perms.application.add_task %}
                    <form action="{% url 'task_assign' task.pk %}" method="POST">{% csrf_token %}
                    {% else %}
                    <form action="{% url 'task_authenticate_assign' task.pk %}" method="GET">
                    {% endif %}
                    <button class="btn waves-effect waves-light indigo lighten-1" type="submit">Weź zadanie
                    <i class="material-icons right">send</i>
                    </button>
                    </form>
                {% endif %}
                </div>
                {% if task.status == task.APPROVED %}
                <div class="row">
                    <div class="col s12"> <h4> Wykonawca zadania:</h4></div>
                    <div class="col s12"> <span class="flow-text" style="font-size: 1.5em"> {{ task.receiver }} </span> </div>
                </div>
                <div class="row">
                    <div class="col s12"> <h4> Data wykonania zadania:</h4></div>
                    <div class="col s12"> <span class="flow-text" style="font-size: 1.5em"> {{ task.mod_date }} </span> </div>
                </div>
                {% endif %}
            </div>
       </div>
    </div>
</main>
{% endblock main %}

codingchallenge/application/templates/application/task_form.html
{% extends "application/index.html" %}
{% load static %}

{% block title %}
<title> Dodaj zadanie</title>
{% endblock title %}


{% block main %}
<main class="valign-wrapper">
  <div class="row">
    <div class="col s12">
      <div class="card">
        <div class="card-content">
          <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="input-field col s12">
                  {{ form.title.errors }} {{ form.title }}
                  <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
                </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                {{ form.description.errors }} {{ form.description }}
                <label for="{{ form.desription.id_for_label }}">{{ form.description.label }}</label>
              </div>
            </div>

            <div class = "row">
              <div class="col s12">
                 <label for="{{ form.value.id_for_label }}"> {{ form.value.label }}</label>
                 <p class = "range-field">
                    {{ form.value.errors }} {{ form.value }}
                 </p>
              </div>
            </div>

            <div class="center-align">
              <button class="btn waves-effect waves-light indigo " type="submit" value="Submit">Dodaj zadanie
                <i class="material-icons right">send</i>
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock main %}